export { default as Home } from './Home';
export { default as About } from './About';
export { default as Login } from './Login';
export { default as Logout} from './Logout';
export { default as Join } from './Join';
export { default as Board } from './Board';
export { default as Board_Category } from './Board_Category';
export { default as Post } from './Post';
export { default as Post_input } from './Post_input';
export { default as Post_modify } from './Post_modify';
export { default as Intro } from './Intro';
export { default as Mypage } from './Mypage';
export { default as Modifyinfo } from './Modifyinfo';
export { default as Passfail } from './Passfail';
export { default as Photos } from './Photos';
